# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.


# Basic Site Settings
locale                   : "en-US"
title                    : "Gang Zhao | Flood Hydro Group"
title_separator          : "-"
name                     : &name "ZHAO Gang"
description              : &description "Gang Zhao is an independent principal investigator and Assistant Professor at Tokyo Institute of Technology working on flood modelling, hydrodynamics, artificial intelligence, mountain flash floods, river floods, and urban floods."
url                      : https://gangzhao-hydro.github.io # the base hostname & protocol for your site
baseurl                  : "/website" # the subpath of your GitHub Pages project site
repository               : "gangzhao-hydro/website"


# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "profile.jpg"
  name             : "ZHAO GANG"
  pronouns         : # example: "she/her"  
  bio              : "Independent PI & Assistant Professor"
  location         : "Tokyo"
  employer         : "Tokyo Institute of Technology"
  uri              : # URL
  email            : "zhao.g.ag@m.titech.ac.jp" 


  # Academic websites
  arxiv            : # URL - Update with the correct link to your profile
  googlescholar    : "https://scholar.google.com/citations?user=2UcV-9kAAAAJ&hl=en&oi=sra"
  impactstory      : # URL
