name: Update publications (OpenAlex)
on:
  schedule:
    - cron: '0 15 * * 1'   # 每周一 15:00 UTC（周二 0:00 JST 左右）
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests
      - name: Run updater
        env:
          ORCID: 0000-0002-0278-502X
          YEARS: '5'
        run: python scripts/update_publications_openalex.py
      - name: Commit changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/pubs_openalex.json || true
          git commit -m "chore: update publications from OpenAlex" || echo "No changes"
          git push
